name: ci
on: [push]
jobs:
  typos:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: Spell checking over all files
      uses: crate-ci/typos@master
      with:
        config: .typos-config.toml

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ubuntu:23.04
    steps:
      - name: Install packages
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y build-essential curl unzip git wget gcovr
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download & Unpack sonar
        shell: bash
        run: |
          curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -o build-wrapper-linux-x86.zip

      - name: Run build wrapper
        shell: bash
        run: build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir cfamily-output make all

      - name: Run executables and calculate coverage
        shell: bash
        run: |
          ./build/unit-tests
          ./build/unit-tests-address-undefined
          ./build/unit-tests-thread
          ./build/good-address-undefined
          ./build/good-thread
          gcovr --exclude-throw-branches --exclude-unreachable-branches --sonarqube coverage.xml -r .

      - name: Run scanner
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          sonar-scanner-4.8.0.2856-linux/bin/sonar-scanner
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=hamdor
          -Dsonar.projectKey=Hamdor_task
          -Dsonar.cfamily.build-wrapper-output=cfamily-output
          -Dsonar.cfamily.threads=2
          -Dsonar.cfamily.cache.enabled=false
          -Dsonar.coverageReportPaths=coverage.xml
          -Dsonar.scm.provider=git
          -Dsonar.exclusions=tests/**
          -Dsonar.coverage.exclusions=tests/**,src/main.cpp
