name: sonar-scan
on: [push]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: ubuntu:20.10
    steps:
      - name: Install packages
        shell: bash
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update && apt install -y build-essential curl unzip git
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download & Unpack sonar
        shell: bash
        run: |
          curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip
          curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -o build-wrapper-linux-x86.zip

      - name: Run build wrapper
        shell: bash
        run: build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir cfamily-output make

      - name: Run scanner
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=hamdor
          -Dsonar.projectKey=Hamdor_task
          -Dsonar.cfamily.build-wrapper-output=cfamily-output
          -Dsonar.cfamily.threads=1
          -Dsonar.cfamily.cache.enabled=false
          -Dsonar.scm.provider=git
